Repository GSG-G10/bastta, pull requests merged in 2021-11, with the labels that each got.

#5 Project Setup
  .eslintrc.json
  .gitignore
  .vscode/settings.json
  client/.eslintrc.json
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/public/assets/basttaLogo.png
  client/public/index.html
  client/src/App.jsx
  client/src/components/index.jsx
  client/src/index.css
  client/src/index.css.map
  client/src/index.jsx
  client/src/index.scss
  client/src/pages/index.jsx
  client/src/store/actions/index.js
  client/src/store/reducers/index.js
  package-lock.json
  package.json
  server/__test__/index.test.js
  server/src/app.js
  server/src/controllers/auth/index.js
  server/src/controllers/index.js
  server/src/database/config/build.js
  server/src/database/config/build.sql
  server/src/database/config/databaseConfig.sql
  server/src/database/config/fakeData.sql
  server/src/database/connection/index.js
  server/src/database/queries/index.js
  server/src/index.js
  server/src/middlewares/index.js
  server/src/routes/index.js
  server/src/utils/index.js
Labels: Done

#6 Write the project's readme file
  README.md
Labels: Done

#11 create database schema
  server/src/database/config/build.sql
Labels: Done, Back-End, Database

#32 Database Configuration
  server/src/database/config/_build.js
  server/src/database/config/_databaseConfig.sql
  server/src/database/config/build.js
  server/src/database/config/build.sql
  server/src/database/connection/index.js
Labels: Done, Back-End, Database

#33 12 generate fake data
  server/src/database/config/fakeData.sql
Labels: In Progress, Back-End, Database

#47 customize react bootstrap theme
  client/src/index.css
  client/src/index.css.map
  client/src/index.scss
Labels: Awaiting Review

#45 Handle CLient and Server Errors
  server/__test__/index.test.js
  server/src/controllers/errors/client-errors.js
  server/src/controllers/errors/index.js
  server/src/controllers/errors/server-errors.js
  server/src/controllers/index.js
  server/src/routes/index.js
Labels: Done, Back-End

#48 Handle user and admin logout
  server/__test__/index.test.js
  server/src/controllers/auth/index.js
  server/src/controllers/auth/logout/admin-logout.js
  server/src/controllers/auth/logout/index.js
  server/src/controllers/auth/logout/user-logout.js
  server/src/controllers/index.js
  server/src/routes/index.js
Labels: Awaiting Review, Back-End, route

#49 Get One Product Route
  .eslintrc.json
  .github/workflows/node.js.yml
  package-lock.json
  package.json
  server/__test__/index.test.js
  server/src/controllers/index.js
  server/src/controllers/products/get-one-product.js
  server/src/controllers/products/index.js
  server/src/database/config/_build.js
  server/src/database/connection/index.js
  server/src/database/queries/find-product-by-id.js
  server/src/database/queries/index.js
  server/src/routes/index.js
Labels: Awaiting Review, Back-End, route

#50 create slider #17
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/assets/bg-slider.jpg
  client/src/assets/code.jpg
  client/src/components/index.jsx
  client/src/components/silder/index.jsx
  client/src/components/silder/style.scss
  client/src/pages/home/index.jsx
  client/src/pages/home/style.css
  client/src/pages/index.jsx
Labels: Awaiting Review, Front-End, component

#43 Set the product in favorite schema using user id and product id
  server/__test__/index.test.js
  server/src/controllers/index.js
  server/src/controllers/products/index.js
  server/src/controllers/products/product-to-fav.js
  server/src/database/queries/index.js
  server/src/database/queries/products/index.js
  server/src/database/queries/products/newFavorites.js
  server/src/routes/index.js
Labels: Awaiting Review, Back-End

#52 Get pending and public products for dashboard page
  server/__test__/index.test.js
  server/src/controllers/index.js
  server/src/controllers/products/get-dashboard-products.js
  server/src/controllers/products/index.js
  server/src/database/queries/get-dashboard-products.js
  server/src/database/queries/index.js
  server/src/middlewares/check-admin.js
  server/src/middlewares/index.js
  server/src/routes/index.js
  server/src/utils/jwt/index.js
Labels: Done, Back-End

#53 Get users for dashboard
  server/src/controllers/index.js
  server/src/controllers/users/get-all-users.js
  server/src/controllers/users/index.js
  server/src/database/queries/index.js
  server/src/database/queries/products/find-product-by-id.js
  server/src/database/queries/products/get-dashboard-products.js
  server/src/database/queries/products/index.js
  server/src/database/queries/users/get-all-users.js
  server/src/database/queries/users/index.js
  server/src/routes/index.js
Labels: Done, Back-End, administration

#54 Edit get one product query to return username
  server/__test__/index.test.js
  server/src/database/queries/products/find-product-by-id.js
Labels: Done, Back-End, Database

#55 8 landing page route
  server/__test__/index.test.js
  server/src/controllers/index.js
  server/src/controllers/products/get-landing-products.js
  server/src/controllers/products/index.js
  server/src/database/queries/index.js
  server/src/database/queries/products/get-all-approved-products.js
  server/src/database/queries/products/get-landing-products.js
  server/src/database/queries/products/get-products-by-section.js
  server/src/database/queries/products/index.js
  server/src/routes/index.js
Labels: Done

#58 create admin login route
  server/src/controllers/auth/index.js
  server/src/controllers/auth/login/admin-login.js
  server/src/controllers/auth/login/index.js
  server/src/controllers/index.js
  server/src/routes/index.js
Labels: Awaiting Review

#59 25 delete user
  server/__test__/index.test.js
  server/src/controllers/index.js
  server/src/controllers/users/delete-user.js
  server/src/controllers/users/index.js
  server/src/database/queries/index.js
  server/src/database/queries/users/find-user-by-id.js
  server/src/database/queries/users/index.js
  server/src/database/queries/users/remove-user.js
  server/src/routes/admin.js
  server/src/routes/index.js
  server/src/routes/products.js
  server/src/routes/users.js
Labels: Done, Back-End, administration

#56 9 delete favorite
  server/__test__/index.test.js
  server/src/controllers/index.js
  server/src/controllers/products/delete-favourite.js
  server/src/controllers/products/index.js
  server/src/database/queries/favourites/delete-fav.js
  server/src/database/queries/favourites/find-fav.js
  server/src/database/queries/favourites/index.js
  server/src/database/queries/index.js
  server/src/middlewares/check-sign-in.js
  server/src/middlewares/index.js
  server/src/routes/products.js
Labels: Done

#62 61 change design system
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.jsx
  client/src/index.css
  client/src/index.jsx
  client/src/index.scss
  client/src/mui-modules.js
  client/src/pages/home/index.jsx
  client/src/pages/home/style.css
  client/src/theme.js
  package.json
Labels: Done

#60 16 Publish product
  server/__test__/index.test.js
  server/src/controllers/index.js
  server/src/controllers/products/get-one-product.js
  server/src/controllers/products/index.js
  server/src/controllers/products/publish-product.js
  server/src/database/queries/index.js
  server/src/database/queries/products/find-product-by-id.js
  server/src/database/queries/products/index.js
  server/src/database/queries/products/publish-product.js
  server/src/routes/admin.js
Labels: Done, Back-End, administration

#64 14 Search Products
  server/src/controllers/index.js
  server/src/controllers/products/index.js
  server/src/controllers/products/search-products.js
  server/src/database/queries/index.js
  server/src/database/queries/products/index.js
  server/src/database/queries/products/search-products.js
  server/src/routes/products.js
Labels: Done, Back-End, route

#63 37 profile products
  server/__test__/index.test.js
  server/src/controllers/index.js
  server/src/controllers/products/get-profile-products.js
  server/src/controllers/products/index.js
  server/src/database/queries/index.js
  server/src/database/queries/products/index.js
  server/src/database/queries/products/profile-products-query.js
  server/src/routes/products.js
Labels: Awaiting Review

#65 26 Signup
  server/src/controllers/auth/index.js
  server/src/controllers/auth/signup/index.js
  server/src/controllers/index.js
  server/src/database/queries/index.js
  server/src/database/queries/users/add-new-user.js
  server/src/database/queries/users/check-account.js
  server/src/database/queries/users/index.js
  server/src/middlewares/index.js
  server/src/middlewares/set-cookie.js
  server/src/routes/users.js
  server/src/utils/b-crypt/index.js
  server/src/utils/validation/index.js
  server/src/utils/validation/signup-schema-validation.js
Labels: Awaiting Review, Back-End, route

#57 38 delete product
  server/src/controllers/index.js
  server/src/controllers/products/delete-product.js
  server/src/controllers/products/index.js
  server/src/database/queries/index.js
  server/src/database/queries/products/delete-product-query.js
  server/src/database/queries/products/index.js
  server/src/routes/products.js
Labels: Awaiting Review

#66 create login controller
  server/src/controllers/auth/index.js
  server/src/controllers/auth/login/index.js
  server/src/controllers/auth/login/user-login.js
  server/src/controllers/index.js
  server/src/database/queries/users/check-account.js
  server/src/routes/users.js
  server/src/utils/validation/index.js
  server/src/utils/validation/login-schema.js
Labels: Done

#68 67 protected tests
  server/__test__/index.test.js
  server/src/database/config/fakeData.sql
Labels: Awaiting Review

#71 edit style slider #70
  client/package-lock.json
  client/src/components/silder/index.jsx
  client/src/components/silder/style.css
  client/src/pages/home/index.jsx
Labels: Done, Front-End

#72 10 post product
  package-lock.json
  package.json
  server/src/controllers/index.js
  server/src/controllers/products/index.js
  server/src/controllers/products/post-product.js
  server/src/database/queries/index.js
  server/src/database/queries/products/index.js
  server/src/database/queries/products/post-product-query.js
  server/src/routes/products.js
  server/src/utils/aws/index.js
  server/src/utils/validation/index.js
  server/src/utils/validation/post-product-schema.js
Labels: Done

#73 Create Footer
  client/src/App.jsx
  client/src/components/footer/index.jsx
  client/src/components/footer/items-component/index.jsx
  client/src/components/footer/items-component/item-one.jsx
  client/src/components/footer/items-component/item-three.jsx
  client/src/components/footer/items-component/item-two.jsx
  client/src/components/footer/style.js
  client/src/components/footer/utils/sections.js
Labels: Done, Front-End, component

#75 create page Doc #21
  client/src/App.jsx
  client/src/components/cardDoc/index.jsx
  client/src/components/cardDoc/style.css
  client/src/components/index.jsx
  client/src/pages/document/index.jsx
  client/src/pages/home/index.jsx
  client/src/pages/index.jsx
Labels: Done, Front-End

#74 36 get favs
  server/__test__/index.test.js
  server/src/controllers/favorites/delete-favourite.js
  server/src/controllers/favorites/get-favs.js
  server/src/controllers/favorites/index.js
  server/src/controllers/favorites/product-to-fav.js
  server/src/controllers/index.js
  server/src/controllers/products/index.js
  server/src/database/queries/favourites/get-user-favs.js
  server/src/database/queries/favourites/index.js
  server/src/database/queries/index.js
  server/src/routes/products.js
Labels: Done

#77 Create admin delete route
  server/src/controllers/index.js
  server/src/controllers/products/admin-delete-product.js
  server/src/controllers/products/index.js
  server/src/routes/admin.js
Labels: Done, Back-End, route

#78 35 pagination
  server/src/controllers/index.js
  server/src/controllers/products/get-landing-products.js
  server/src/controllers/products/get-pagination.js
  server/src/controllers/products/index.js
  server/src/database/queries/products/get-products-by-section.js
  server/src/routes/products.js
Labels: Awaiting Review

#69 51 dashboard
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/assets/brand/Logo_Transparent.svg
  client/src/assets/brand/logo.jpg
  client/src/assets/index.js
  client/src/components/admin/dashboard/Cards.jsx
  client/src/components/admin/dashboard/ConfirmRequest.jsx
  client/src/components/admin/dashboard/ImageModal.jsx
  client/src/components/admin/dashboard/Table.jsx
  client/src/components/admin/dashboard/style.js
  client/src/components/admin/index.js
  client/src/components/cardDoc/index.jsx
  client/src/components/cardDoc/style.css
  client/src/components/index.jsx
  client/src/mui-modules.js
  client/src/pages/Dashboard/Dashboard-Login/index.js
  client/src/pages/Dashboard/Dashboard-Login/style.js
  client/src/pages/Dashboard/Layout/PublicView.jsx
  client/src/pages/Dashboard/Layout/Sidbar.jsx
  client/src/pages/Dashboard/Layout/TableData.jsx
  client/src/pages/Dashboard/Layout/index.js
  client/src/pages/Dashboard/Layout/style.js
  client/src/pages/Dashboard/index.js
  client/src/pages/error/NotFound.jsx
  client/src/pages/home/index.jsx
  client/src/pages/index.jsx
  client/src/store/actions/dashboard-actions.js
  client/src/store/actions/index.js
  client/src/store/reducers/dashboard-reducer.js
  client/src/store/reducers/index.js
  client/src/style-components.js
  client/src/theme.js
  package.json
  server/src/controllers/auth/login/admin-login.js
  server/src/middlewares/check-admin.js
Labels: Awaiting Review

#80 create single product component #20
  client/package-lock.json
  client/package.json
  client/src/components/index.jsx
  client/src/components/singleProduct/detailes/index.jsx
  client/src/components/singleProduct/detailes/style.css
  client/src/components/singleProduct/index.jsx
  client/src/components/singleProduct/slider/index.jsx
  client/src/components/singleProduct/slider/style.css
  client/src/index.css
  client/src/mui-modules.js
  client/src/pages/index.jsx
  client/src/pages/single/index.jsx
Labels: Done, Front-End

#81 79 Create Errors Pages
  client/src/App.jsx
  client/src/components/footer/index.jsx
  client/src/mui-modules.js
  client/src/pages/error/NotFound.jsx
  client/src/pages/errors/404.jsx
  client/src/pages/errors/500.jsx
  client/src/pages/errors/index.jsx
  client/src/pages/errors/styles.js
  client/src/pages/home/index.jsx
  client/src/pages/index.jsx
Labels: Done, Front-End

#83 product card and products containers
  client/package-lock.json
  client/src/App.jsx
  client/src/components/ProductCard/index.jsx
  client/src/components/ProductCard/style.js
  client/src/components/ProductsContainer/index.jsx
  client/src/components/ProductsContainer/style.js
  client/src/components/silder/style.css
  client/src/mui-modules.js
  client/src/pages/home/index.jsx
  package-lock.json
Labels: Awaiting Review, Front-End
