Repository GSG-G10/bastta, pull requests merged in 2021-12, with the labels that each got.

#84 create classified product card component #31
  client/src/App.jsx
  client/src/components/classifiedCard/index.jsx
  client/src/components/classifiedCard/style.css
  client/src/components/index.jsx
  client/src/components/singleProduct/detailes/index.jsx
  client/src/mui-modules.js
  client/src/pages/classifiedProduct/index.jsx
  client/src/pages/index.jsx
Labels: Awaiting Review, Front-End, component

#87 Initialize auth route
  server/src/controllers/index.js
  server/src/controllers/users/get-user-id.js
  server/src/controllers/users/index.js
  server/src/routes/users.js
Labels: Done, Back-End, route

#90 create Ads cards #82
  client/src/assets/LOGO.png
  client/src/assets/LOGO2.png
  client/src/components/ads/index.jsx
  client/src/components/ads/style.js
  client/src/components/adsLoginCard/index.jsx
  client/src/components/adsLoginCard/style.js
  client/src/components/index.jsx
  client/src/pages/home/index.jsx
Labels: Done, Front-End

#92 28 signin signup window
  client/src/App.jsx
  client/src/components/AuthModal/LoginForm.jsx
  client/src/components/AuthModal/RegisterForm.jsx
  client/src/components/AuthModal/Sncakbar.jsx
  client/src/components/AuthModal/index.js
  client/src/components/AuthModal/style.js
  client/src/components/Navbar/index.js
  client/src/components/index.jsx
  client/src/mui-modules.js
  client/src/pages/home/index.jsx
  client/src/store/actions/index.js
  client/src/store/actions/user-actions.js
  client/src/store/reducers/auth.js
  client/src/store/reducers/index.js
  client/src/store/reducers/user-reducer.js
  client/src/theme.js
  client/src/utils/checkAuth.js
  client/src/utils/constants.js
  client/src/utils/index.js
  server/__test__/index.test.js
  server/src/controllers/auth/login/user-login.js
  server/src/controllers/auth/signup/index.js
  server/src/controllers/errors/schema-errors.js
  server/src/middlewares/check-sign-in.js
  server/src/middlewares/set-cookie.js
  server/src/utils/validation/login-schema.js
  server/src/utils/validation/signup-schema-validation.js
Labels: Awaiting Review

#86 filter data
  client/src/assets/sections-types/index.js
  client/src/components/filter/Price.jsx
  client/src/components/filter/cities.js
  client/src/components/filter/index.jsx
  client/src/components/filter/style.js
  client/src/components/index.jsx
  client/src/store/actions/filter-actions.js
  client/src/store/reducers/filter-reducer.js
  client/src/store/reducers/index.js
  server/src/controllers/products/get-landing-products.js
  server/src/database/queries/products/get-all-approved-products.js
Labels: Awaiting Review, Front-End, component

#94 Fix register notifications & AWS required changes
  client/src/components/AuthModal/LoginForm.jsx
  client/src/components/AuthModal/RegisterForm.jsx
  client/src/components/Navbar/SearchBox.jsx
  client/src/utils/constants.js
  server/src/utils/aws/index.js
  server/src/utils/validation/signup-schema-validation.js
Labels: Done

#96 Build sections list
  client/src/components/Navbar/style.js
  client/src/components/SectionList/index.jsx
  client/src/components/SectionList/style.js
  client/src/components/index.jsx
  client/src/pages/home/index.jsx
Labels: Done

#97 create pagination #91
  client/src/App.jsx
  client/src/components/SectionList/index.jsx
  client/src/components/cardDoc/index.jsx
  client/src/components/classifiedCard/index.jsx
  client/src/components/classifiedCard/style.css
  client/src/components/paginaion/index.jsx
  client/src/components/paginaion/style.css
  server/src/controllers/products/get-pagination.js
  server/src/database/queries/products/get-products-by-section.js
Labels: Done, Front-End, component

#103 edit search requset #101
  client/src/App.jsx
  client/src/components/Navbar/SearchBox.jsx
  client/src/components/classifiedCard/index.jsx
  client/src/components/classifiedCard/style.css
  client/src/components/filter/Price.jsx
  client/src/components/filter/index.jsx
  client/src/components/filter/style.js
  client/src/components/footer/items-component/item-three.jsx
  client/src/components/paginaion/index.jsx
  client/src/pages/classifiedProduct/index.jsx
  client/src/pages/document/index.jsx
  client/src/pages/single/index.jsx
  server/src/database/queries/products/get-products-by-section.js
Labels: Awaiting Review

#105 Refactor home page
  client/src/components/NewAdsModal/style.js
  client/src/components/ProductsContainer/index.jsx
  client/src/components/admin/dashboard/Cards.jsx
  client/src/components/admin/dashboard/ImageModal.jsx
  client/src/pages/home/api.js
  client/src/pages/home/index.jsx
  server/src/controllers/products/get-landing-products.js
Labels: Done, Front-End

#107 Fix Bugs
  client/src/components/AuthModal/LoginForm.jsx
  client/src/components/AuthModal/RegisterForm.jsx
  client/src/components/Navbar/Dropdown.jsx
  client/src/components/SectionList/index.jsx
  client/src/components/filter/Price.jsx
  client/src/components/filter/index.jsx
  client/src/components/filter/style.js
  client/src/components/paginaion/index.jsx
  client/src/components/singleProduct/slider/index.jsx
Labels: Done, Front-End

#108 Fix Deploy bugs
  client/package-lock.json
  client/package.json
  client/src/components/filter/style.js
  package-lock.json
  package.json
Labels: Done

#110 Change css to js
  client/src/assets/code.jpg
  client/src/assets/index.js
  client/src/components/Navbar/index.js
  client/src/components/cardDoc/index.jsx
  client/src/components/cardDoc/style.css
  client/src/components/cardDoc/style.js
  client/src/components/classifiedCard/index.jsx
  client/src/components/classifiedCard/style.css
  client/src/components/classifiedCard/style.js
  client/src/components/paginaion/index.jsx
  client/src/components/paginaion/style.css
  client/src/components/pagination/index.jsx
  client/src/components/pagination/style.js
  client/src/components/silder/index.jsx
  client/src/components/singleProduct/detailes/index.jsx
  client/src/components/singleProduct/detailes/style.css
  client/src/components/singleProduct/index.jsx
  client/src/components/singleProduct/slider/index.jsx
  client/src/components/singleProduct/slider/style.css
  client/src/components/singleProduct/slider/style.js
  client/src/pages/home/style.css
  client/src/store/reducers/filter-reducer.js
  server/src/database/config/fakeData.sql
Labels: Done, Front-End

#113 112 filter route
  client/src/components/classifiedCard/index.jsx
  client/src/components/filter/Price.jsx
  client/src/components/filter/index.jsx
  client/src/components/paginaion/index.jsx
  client/src/components/profileCards/Favs.css
  server/src/controllers/index.js
  server/src/controllers/products/get-filter.js
  server/src/controllers/products/index.js
  server/src/database/queries/index.js
  server/src/database/queries/products/filter-query.js
  server/src/database/queries/products/index.js
  server/src/routes/products.js
  server/src/utils/validation/filter.js
  server/src/utils/validation/index.js
Labels: Awaiting Review

#115 Edit CSS styles
  client/src/components/ProductCard/style.js
  client/src/components/cardDoc/index.jsx
  client/src/components/classifiedCard/index.jsx
  client/src/components/footer/items-component/item-two.jsx
  client/src/components/paginaion/index.jsx
  client/src/components/pagination/index.jsx
  client/src/components/pagination/style.js
  client/src/components/profileCards/Cards.jsx
  client/src/components/profileCards/Favs.css
  client/src/components/profileCards/index.jsx
  client/src/components/profileCards/style.css
  client/src/components/profileCards/style.js
  client/src/components/singleProduct/detailes/index.jsx
  client/src/components/singleProduct/detailes/style.css
  client/src/components/singleProduct/detailes/style.js
  client/src/store/reducers/auth.js
Labels: Done, Front-End

#117 edit style cards and login form #116
  client/src/components/AuthModal/LoginForm.jsx
  client/src/components/AuthModal/RegisterForm.jsx
  client/src/components/AuthModal/style.js
  client/src/components/pagination/style.js
Labels: Done

#118 Edit images in fake data
  client/src/assets/sections-types/index.js
  server/src/database/config/fakeData.sql
Labels: Done

#120 fix responsive and styles issues
  client/public/index.html
  client/src/components/Navbar/style.js
  client/src/components/ProductCard/style.js
  client/src/components/SectionList/style.js
  client/src/components/ads/index.jsx
  client/src/components/ads/style.js
  client/src/components/adsLoginCard/index.jsx
  client/src/components/adsLoginCard/style.js
  client/src/components/filter/index.jsx
  client/src/components/filter/style.js
  client/src/components/footer/index.jsx
  client/src/components/footer/items-component/item-one.jsx
  client/src/components/footer/items-component/item-three.jsx
  client/src/components/footer/items-component/item-two.jsx
  client/src/components/footer/style.js
  client/src/components/pagination/index.jsx
  client/src/components/pagination/style.js
  client/src/components/silder/style.css
  client/src/components/singleProduct/detailes/index.jsx
  client/src/components/singleProduct/detailes/style.js
  client/src/components/singleProduct/index.jsx
  client/src/components/singleProduct/slider/index.jsx
  client/src/components/singleProduct/slider/style.js
  client/src/mui-modules.js
  client/src/theme.js
Labels: Done

#122 fix about page responsive
  client/src/components/cardDoc/index.jsx
  client/src/components/cardDoc/style.js
  client/src/components/pagination/style.js
Labels: Awaiting Review, Front-End

#124 Create Chat Page instead of 404
  client/src/App.jsx
  client/src/components/Navbar/index.js
  client/src/components/silder/style.css
  client/src/pages/chat/index.jsx
  client/src/pages/chat/style.js
  client/src/pages/index.jsx
Labels: Done, Front-End

#119 98 post product form
  client/src/assets/index.js
  client/src/assets/types-icons/appliances.svg
  client/src/assets/types-icons/car.svg
  client/src/assets/types-icons/elctronics.svg
  client/src/assets/types-icons/furniture.svg
  client/src/assets/types-icons/house.svg
  client/src/assets/types-icons/index.js
  client/src/assets/types-icons/service.svg
  client/src/assets/types-icons/sports.svg
  client/src/components/NewAdsModal/AdsType.jsx
  client/src/components/NewAdsModal/Form.jsx
  client/src/components/NewAdsModal/NewAdsForm.jsx
  client/src/components/NewAdsModal/index.jsx
  client/src/components/NewAdsModal/style.js
  client/src/components/admin/dashboard/Table.jsx
  client/src/mui-modules.js
  client/src/utils/constants.js
  client/src/utils/index.js
  client/src/utils/types.js
  package-lock.json
  package.json
  server/src/controllers/products/post-product.js
  server/src/database/queries/products/post-product-query.js
  server/src/routes/products.js
  server/src/utils/aws/index.js
  server/src/utils/validation/post-product-schema.js
Labels: Awaiting Review, Front-End

#126 125 fix bugs
  client/package-lock.json
  client/src/components/NewAdsModal/Form.jsx
  client/src/components/NewAdsModal/NewAdsForm.jsx
  client/src/mui-modules.js
  package-lock.json
  package.json
  server/src/routes/products.js
Labels: Done

#127 Edit filter & s3 upload
  client/src/components/filter/index.jsx
  client/src/components/singleProduct/slider/index.jsx
  client/src/style-components.js
Labels: Done, Front-End
